# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import cortex_pb2 as cortex__pb2

class CortexStub(object):
    """Missing associated documentation comment in .proto file."""
    def __init__(self, channel):
        self.ParseIntent = channel.unary_unary(
                '/cortex.Cortex/ParseIntent',
                request_serializer=cortex__pb2.IntentRequest.SerializeToString,
                response_deserializer=cortex__pb2.IntentResponse.FromString,
                )
        self.GenerateUI = channel.unary_unary(
                '/cortex.Cortex/GenerateUI',
                request_serializer=cortex__pb2.UIRequest.SerializeToString,
                response_deserializer=cortex__pb2.UIResponse.FromString,
                )

class CortexServicer(object):
    """Missing associated documentation comment in .proto file."""
    def ParseIntent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    def GenerateUI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

def add_CortexServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseIntent,
                    request_deserializer=cortex__pb2.IntentRequest.FromString,
                    response_serializer=cortex__pb2.IntentResponse.SerializeToString,
            ),
            'GenerateUI': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateUI,
                    request_deserializer=cortex__pb2.UIRequest.FromString,
                    response_serializer=cortex__pb2.UIResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cortex.Cortex', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

class Cortex(object):
    @staticmethod
    def ParseIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cortex.Cortex/ParseIntent',
            cortex__pb2.IntentRequest.SerializeToString,
            cortex__pb2.IntentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
    @staticmethod
    def GenerateUI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cortex.Cortex/GenerateUI',
            cortex__pb2.UIRequest.SerializeToString,
            cortex__pb2.UIResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
