# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cortex.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_sym_db = _symbol_database.Default()
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ccortex.proto\x12\x06\x63ortex\"\x82\x01\n\rIntentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12:\n\x07\x63ontext\x18\x02 \x03(\x0b\x32).cortex.IntentRequest.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"F\n\x0eIntentResponse\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x12\n\nparams_json\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\"\x82\x01\n\tUIRequest\x12\x11\n\tintent_id\x18\x01 \x01(\t\x12.\n\x0b\x63onstraints\x18\x02 \x03(\x0b\x32\x19.cortex.UIRequest.ConstraintsEntry\x1a\x32\n\x10\x43onstraintsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\">\n\nUIResponse\x12\x1c\n\x14\x63omponent_tree_json\x18\x01 \x01(\t\x12\x0e\n\x06\x61ssets\x18\x02 \x03(\t2x\n\x06\x43ortex\x12<\n\x0bParseIntent\x12\x15.cortex.IntentRequest\x1a\x16.cortex.IntentResponse\x12\x30\n\nGenerateUI\x12\x11.cortex.UIRequest\x1a\x12.cortex.UIResponseb\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cortex_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INTENTREQUEST_CONTEXTENTRY']._options = None
  _globals['_INTENTREQUEST_CONTEXTENTRY']._serialized_options = b'8\x01'
  _globals['_UIREQUEST_CONSTRAINTSENTRY']._options = None
  _globals['_UIREQUEST_CONSTRAINTSENTRY']._serialized_options = b'8\x01'
  _globals['_INTENTREQUEST']._serialized_start=25
  _globals['_INTENTREQUEST']._serialized_end=155
  _globals['_INTENTREQUEST_CONTEXTENTRY']._serialized_start=97
  _globals['_INTENTREQUEST_CONTEXTENTRY']._serialized_end=143
  _globals['_INTENTRESPONSE']._serialized_start=157
  _globals['_INTENTRESPONSE']._serialized_end=227
  _globals['_UIREQUEST']._serialized_start=230
  _globals['_UIREQUEST']._serialized_end=360
  _globals['_UIREQUEST_CONSTRAINTSENTRY']._serialized_start=97
  _globals['_UIREQUEST_CONSTRAINTSENTRY']._serialized_end=143
  _globals['_UIRESPONSE']._serialized_start=362
  _globals['_UIRESPONSE']._serialized_end=424
  _globals['_CORTEX']._serialized_start=426
  _globals['_CORTEX']._serialized_end=546
